table_prefix: web_
namespace:
    - Clips\Web
route_rules:
    - /application/rules/route.rules
    - /rules/route.rules
filters:
    - Widget
    - Rules
    - Form
    - Scss
    - Css
    - SmartyView
    - MustacheView
    - JsonView
    - DirectView
helpers:
    - web
    - html
defualt_view: Smarty
widget_cache: true
sass_preload:
    - variables
logger:
    handlers:
        Stream:
            - php://stdin
            - debug
        FirePHP:
            - debug
        ChromePHP:
            - debug
        RotatingFile:
            - /tmp/clips-web.log
            - 4
            - debug
        processors:
            - Git
            - PsrLogMessage
            - Introspection
            - Tag
datasources:
    mysql:
        table_prefix: web_
        type: mysqli
        database: web_dev
