namespace:
    - Clips\Web
route_rules:
    - /application/rules/route.rules
    - /rules/route.rules
filters:
    - Widget
    - Rules
    - Form
    - Scss
    - Css
    - SmartyView
    - MustacheView
    - JsonView
    - DirectView
helpers:
    - web
    - html
default_view: Smarty
widget_cache: true
sass_preload:
    - variables
models:
    user:
        datasource: clips
    group:
        datasource: clips

logger:
    handlers:
        Stream:
            - php://stdin
            - debug
        FirePHP:
            - debug
        ChromePHP:
            - debug
        RotatingFile:
            - /tmp/clips-web.log
            - 4
            - debug
        processors:
            - Git
            - PsrLogMessage
            - Introspection
            - Tag
datasources:
    default: clips
    mysql:
        type: MySQLi
        database: web_dev
    clips:
        type: clips
        datasource: mysql
        table_prefix: web_
        filters:
            - prefix
